name: build_and_push_to_main

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: node setup
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: npm install
        run: npm install --legacy-peer-deps

      - name: build
        run: npm run build

      - name: remove dist from .gitignore
        run: sed -i '/dist/d' .gitignore
      
      - name: commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git stash --include-untracked
          git checkout main
          if git stash list | grep -q "stash@{0}"; then
            git stash pop
          fi
          git add .
          git status
          if ! git diff-index --quiet HEAD; then
            git commit -m "actions: build"
          fi

      - name: push
        uses: nick-fields/retry@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          max_attempts: 3
          retry_wait_seconds: 10
          timeout_minutes: 3
          command: git push origin HEAD:main --force

      - name: add dist to .gitignore
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "dist" >> .gitignore
          git add .gitignore
          git commit -m "actions: add dist to .gitignore"

      - name: push ignore
        uses: nick-fields/retry@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          max_attempts: 3
          retry_wait_seconds: 10
          timeout_minutes: 3
          command: git push origin HEAD:main --force